{% set version = '0.1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qs2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qs2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qs2/qs2_{{ version }}.tar.gz
  sha256: c2dec8a8643db08ae6e496fd775fe723aba86742d9fb3fc93b65aa640e162f04

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]
    - '*/libtbb.*'

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - zstd
    - r-base
    - r-rcpp
    - r-rcppparallel
    - r-stringfish >=0.15.1
  run:
    - zstd
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcppparallel
    - r-stringfish >=0.15.1

test:
  commands:
    - $R -e "library('qs2')"           # [not win]
    - "\"%R%\" -e \"library('qs2')\""  # [win]

about:
  home: https://github.com/qsbase/qs2
  license: GPL-3.0-only
  summary: 'Streamlines and accelerates the process of saving and loading R objects, improving
    speed and compression compared to other methods. The package provides two compression
    formats: the ''qs2'' format, which uses R serialization via the C API while optimizing
    compression and disk I/O, and the ''qdata'' format, featuring custom serialization
    for slightly faster performance and better compression. Additionally, the ''qs2''
    format can be directly converted to the standard ''RDS'' format, ensuring long-term
    compatibility with future versions of R.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: qs2
# Type: Package
# Title: Efficient Serialization of R Objects
# Version: 0.1.4
# Date: 2024-12-11
# Authors@R: c( person("Travers", "Ching", email = "traversc@gmail.com", role = c("aut", "cre", "cph")), person("Yann", "Collet", role = c("ctb", "cph"), comment = "Yann Collet is the author of the bundled zstd"), person("Facebook, Inc.", role = "cph", comment = "Facebook is the copyright holder of the bundled zstd code"), person("Reichardt", "Tino", role = c("ctb", "cph"), comment = "Contributor/copyright holder of zstd bundled code"), person("Skibinski", "Przemyslaw", role = c("ctb", "cph"), comment = "Contributor/copyright holder of zstd bundled code"), person("Mori", "Yuta", role = c("ctb", "cph"), comment = "Contributor/copyright holder of zstd bundled code"), person("Francesc", "Alted", role = c("ctb", "cph"), comment = "Shuffling routines derived from Blosc library"))
# Maintainer: Travers Ching <traversc@gmail.com>
# Description: Streamlines and accelerates the process of saving and loading R objects, improving speed and compression compared to other methods. The package provides two compression formats: the 'qs2' format, which uses R serialization via the C API while optimizing compression and disk I/O, and the 'qdata' format, featuring custom serialization for slightly faster performance and better compression. Additionally, the 'qs2' format can be directly converted to the standard 'RDS' format, ensuring long-term compatibility with future versions of R.
# License: GPL-3
# LazyData: true
# Biarch: true
# Depends: R (>= 3.5.0)
# Imports: Rcpp, stringfish (>= 0.15.1)
# LinkingTo: Rcpp, stringfish, RcppParallel
# Suggests: knitr, rmarkdown, dplyr, data.table, stringi
# SystemRequirements: GNU make
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# VignetteBuilder: knitr
# Copyright: This package includes code from the 'zstd' library owned by Facebook, Inc. and created by Yann Collet; and code derived from the 'Blosc' library created and owned by Francesc Alted.
# URL: https://github.com/qsbase/qs2
# BugReports: https://github.com/qsbase/qs2/issues
# NeedsCompilation: yes
# Packaged: 2024-12-12 01:03:21 UTC; tching
# Author: Travers Ching [aut, cre, cph], Yann Collet [ctb, cph] (Yann Collet is the author of the bundled zstd), Facebook, Inc. [cph] (Facebook is the copyright holder of the bundled zstd code), Reichardt Tino [ctb, cph] (Contributor/copyright holder of zstd bundled code), Skibinski Przemyslaw [ctb, cph] (Contributor/copyright holder of zstd bundled code), Mori Yuta [ctb, cph] (Contributor/copyright holder of zstd bundled code), Francesc Alted [ctb, cph] (Shuffling routines derived from Blosc library)
# Repository: CRAN
# Date/Publication: 2024-12-12 06:00:02 UTC
